#! /bin/sh
git pull origin master \
&& php app/console cache:clear --env=prod \
&& php app/console assets:install web --symlink \
&& php app/console assetic:dump --env=prod \
&& chmod -R 777 app/cache app/logs
