imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_httponly: true
        cookie_lifetime: 604800
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ZghFEBundle, ZghMsgBundle, FOSMessageBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    encryption: "%mailer_enc%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:
        type: file
        path: %kernel.root_dir%/spool

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Zgh\FEBundle\Entity\User
    registration:
        confirmation:
            from_email:
                address:        noreply@zaghruta.com
                sender_name:    Registration confirmation
            enabled: true
        form:
            type: zgh_fe_registration_form_type
            validation_groups: ["customRegistration", "Default"]
    profile:
        form:
            validation_groups: ["customProfile", "Default"]
    resetting:
        email:
            from_email:
                address:        noreply@zaghruta.com
                sender_name:    Password resetting
        form:
            validation_groups: ["customResetting", "Default"]
    service:
        mailer: fos_user.mailer.twig_swift

hwi_oauth:
#    name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    http_client:
        verify_peer: false
    connect:
        account_connector: zgh_user_provider
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           1403397396596528
            client_secret:       83f8f7e54bfbb0846d3c5bc91ef60b21
            scope:               "email"
            infos_url:           "https://graph.facebook.com/me?fields=username,relationship_status,first_name,last_name,email,picture.type(square),gender,birthday,link"
            paths:
                first_name:       first_name
                last_name:        last_name
                email:            email
                gender:           gender
                status:           relationship_status
            options:
                display:         popup

fos_js_routing:
    routes_to_expose: [ zgh_fe.user.login_partial, zgh_fe.vendor.login_partial, zgh_fe.user_profile.privacy.set, zgh_fe.like.list, zgh_fe.comment.list, fos_message_thread_view, zgh_fe.notifications, zgh_message_inbox_content, fos_message_list_view, zgh_fe.email_notification.set, fos_user_security_login ]

fos_message:
    db_driver: orm
    thread_class: Zgh\MsgBundle\Entity\Thread
    message_class: Zgh\MsgBundle\Entity\Message
    thread_manager: zgh_message.thread_manager
    message_manager: zgh_message.message_manager
    provider: zgh_message.provider
    twig_extension: zgh_message.twig_extension
    new_thread_form:
        type:               zgh_msg.new_thread_form.type
        handler:            zgh_message.thread_form_handler
    reply_form:
        handler:            zgh_message.message_form_handler

liip_imagine:
    filter_sets:
        my_thumb:
            quality: 100
            filters:
                thumbnail: { size: [561, 700], mode: inset }
        my_widen:
            quality: 100
            filters:
                relative_resize: { widen: 561 }
        my_photos:
            quality: 100
            filters:
                relative_resize: { heighten: 600 }
        my_list_thumb:
            quality: 100
            filters:
                thumbnail: { size: [279, 155], mode: outbound }
        pp_thumb:
            quality: 100
            filters:
                thumbnail: { size: [125, 125], mode: outbound }