security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    acl:
        connection: default
    role_hierarchy:
        ROLE_CUSTOMER:     ROLE_USER
        ROLE_VENDOR:       ROLE_USER
        ROLE_REGISTERED:  [ ROLE_CUSTOMER, ROLE_VENDOR ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: zgh_fe.login_handler_success
                require_previous_session: false
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 2592000 # 30 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: zgh_user_provider
                require_previous_session: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[0-9]+, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/like, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET]}
        - { path: ^/, role: [ ROLE_CUSTOMER, ROLE_VENDOR ]}